# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('moon_ore', models.BooleanField()),
            ],
        ),
    ]
