# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0002_ore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ore',
        ),
    ]
