# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eve_sde', '0002_ore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='eve_sde.Moon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResultOre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField()),
                ('ore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eve_sde.Ore')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituents', to='moon_tracker.ScanResult')),
            ],
        ),
    ]
