# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresultore',
            name='ore',
            field=models.IntegerField(choices=[('Standard Ores', ((1, 'PH1'), (2, 'PH2'))), ('Moon Ores', ((3, 'PH3'), (4, 'PH4')))]),
        ),
    ]
